### ISSUE TITLE
Couldn't find any webpack configurations in any CRA when running `babel-loader-lerna-cra`

### ISSUE THREAD

**Issue by frendyguo-zz** [F1LT3R/babel-loader-lerna-cra#4]
After setting up my `babel-loader-lerna-cra`'s configurations, the loader is able to find the locations of my react app (CRA, not ejected), however it couldn't the `webpack.config` js-es

Is this the expected behaviour?

**Comment by jupadev** [comment]
I'm having the same issue, trying to get webpack.config.dev.js

this is the node module folder
![image](https://user-images.githubusercontent.com/7463397/51339342-f9b8bc80-1a6a-11e9-9321-8a297e22f241.png)

babel-lerna-loader-cra: copying: my-react-app/... webpack.config.dev.js => backup.webpack.config.dev.js 
ENOENT: no such file or directory, stat '/Users/thirdlove-mac/Documents/projects/monorepos/button/packages/my-react-app/node_modules/react-scripts/config/webpack.config.dev.js

**Comment by dnsmob** [comment]
i rolled back the dependency of `react-scripts` in the project to version 2.0.5 and it worked fine. it must've been that change as currently CRA uses 2.1.3 and the `webpack.dev` or `webpack.prod` do not exist anymore. there are far more changes than i understand in the configs, so the easy way out is to just roll back the version. cheap solution, but seems to work.

**Comment by frendyguo-zz** [comment]
Yup, I tried using the exact same version of `react-scripts` (2.0.5 in this case), and it worked perfectly

**Comment by frendyguo-zz** [comment]
Closing
